name: Package API specification
on:
  push:
    tags:
      - "v*"
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make tarball
      run: tar -cvzf "appgate-sdp-api-spec-$(echo $GITHUB_REF | grep -oP "v\d+$").tgz" *.y*ml
    - name: Upload tarball
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "*.tgz"